<a href="https://colab.research.google.com/github/MennaAhmed1/python-Exercises/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy

firstArray = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes ", firstArray.itemsize)

Printing Array
[[48304  3932]
 [32752     0]
 [65200  3491]
 [32752     0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes  2


In [2]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)


Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [3]:
import numpy

sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


In [ ]:
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
newArray = sampleArray[::2, 1::2]
print(newArray)

In [4]:
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

for num in numpy.nditer(resultArray, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


In [9]:
import pandas as pd
q = pd.read_csv('/content/CarPrice_Assignment.csv')
w=q.dropna()
print(w)
q.fillna(0,inplace=True)

     car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88

In [10]:
j=pd.read_csv("CarPrice_Assignment.csv")
max=j[['CarName','price']][j.price==j['price'].max()]
print(max)

                            CarName    price
74  buick regal sport coupe (turbo)  45400.0


In [12]:
car = q.groupby('CarName')
x = car.get_group('audi 100 ls')
print(x)

   car_ID  symboling      CarName fueltype aspiration doornumber carbody  \
3       4          2  audi 100 ls      gas        std       four   sedan   

  drivewheel enginelocation  wheelbase  ...  enginesize  fuelsystem  \
3        fwd          front       99.8  ...         109        mpfi   

   boreratio  stroke compressionratio horsepower  peakrpm citympg  highwaympg  \
3       3.19     3.4             10.0        102     5500      24          30   

     price  
3  13950.0  

[1 rows x 26 columns]


In [13]:
q['CarName'].value_counts()

toyota corona           6
toyota corolla          6
peugeot 504             6
subaru dl               4
mitsubishi mirage g4    3
                       ..
mazda glc 4             1
mazda rx2 coupe         1
maxda glc deluxe        1
maxda rx3               1
volvo 246               1
Name: CarName, Length: 147, dtype: int64

In [14]:
x = q.groupby('CarName')
y = x['CarName','price'].max()
print(y)

                                           CarName    price
CarName                                                    
Nissan versa                          Nissan versa   5499.0
alfa-romero Quadrifoglio  alfa-romero Quadrifoglio  16500.0
alfa-romero giulia              alfa-romero giulia  13495.0
alfa-romero stelvio            alfa-romero stelvio  16500.0
audi 100 ls                            audi 100 ls  13950.0
...                                            ...      ...
volvo 246                                volvo 246  22470.0
volvo 264gl                            volvo 264gl  22625.0
volvo diesel                          volvo diesel  18950.0
vw dasher                                vw dasher  11595.0
vw rabbit                                vw rabbit   9980.0

[147 rows x 2 columns]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  
